name: Frontend Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - "starter/frontend/**"
      - ".github/workf**ws/frontend-cd.yaml"
  workflow_d**patch:

jobs:
  lint:
    name: L**t Frontend
    runs-on: ubuntu-la**st

    defaults:
      run:
    **  working-directory: starter/fron**nd

   **teps**      - name: Checkout code
     ** uses: actions/checkout@v4

     ** name: Setup NodeJS
        uses:**ctions/setup-node@v4
        with**          node-version: "16"
    **    cache: "npm"
          cache-**pendency-path: starter/frontend/p**kage-lock.json

      - name: Ins**ll dependencies
        run: npm **

      - name: Run frontend lint**       run: npm run lint

  test:**   name: Test Frontend
    runs-o** ubuntu-latest

    defaults:
   ** run:
       **orking-directory: starter/fronten**
    steps:
     ** name: Checkout code
        uses**actions/checkout@v4

**   ** name: Setup NodeJS
        uses:**ctions/setup-node@v4
        with****       **ode-version: "16"
          cache**"npm"
         **ache-dependency-path: starter/fro**end/package-lock.json

      - na**: Install dependencies
        ru** npm ci

      - name: Run fronte** tests
        run: CI=true npm t**t

  build:
   **ame: Build and Push Frontend Imag**    runs-on: ubuntu-latest
   **eeds:
      - lint
**   ** test

   **utputs:
      image: ${{ steps.im**e.outputs.image }}

**  defaults:
     **un**        working-directory: starte**frontend

    steps:
     ** name: Checkout code
        uses**actions/checkout@v4

      - name**Configure AWS credentials
       **ses**aws-actions/configure-aws-credent**ls@v4
        with:
          aws**ccess-key-id: ${{ secrets.AWS_ACC**S_KEY_ID }}
          aws-secret-**cess-key: ${{ secrets.AWS_SECRET_**CESS_KEY }}
          aws-session**oken: ${{ secrets.AWS_SESSION_TOK** }}
          aws-region: ${{ sec**ts.AWS_REGION }}

      - name: L**in to Amazon ECR
        uses: aw**actions/amazon-ecr-login@v2

    **- name: Build frontend Docker ima**
        run: |
          docker **ild \
           **-build-arg=REACT_APP_MOVIE_API_UR**${{ secrets.REACT_APP_MOVIE_API_U** }} \
            --tag ${{ secre**.AWS_FRONTEND_ECR_REPO }}:${{ git**b.sha }} .

      - name: Push fr**tend Docker image
        run: do**er push ${{ secrets.AWS_FRONTEND_**R_REPO }}:${{ github.sha }}

    **- name: Save frontend image outpu**        id: image
        run: ec** "image=${{ secrets.AWS_FRONTEND_**R_REPO }}:${{ github.sha }}" >> "**ITHUB_OUTPUT"

  deploy:
    name**Deploy Frontend to EKS
    runs-o** ubuntu-latest
    needs:
      -**uild

**  steps:
     ** name: Checkout code
**      uses: actions/checkout@v4

**   ** name: Configure AWS credentials
**     **ses: aws-actions/configure-aws-cr**entials@v4
**     **ith**          aws-access-key-id: ${{ **crets.AWS_ACCESS_KEY_ID }}
      **  aws-secret-access-key: ${{ secr**s.AWS_SECRET_ACCESS_KEY }}
      **  aws-session-token: ${{ secrets.**S_SESSION_TOKEN }}
          aws-**gion: ${{ secrets.AWS_REGION }}

**    - name: Update kubeconfig
   **   run: |
          aws eks updat**kubeconfig \
            --region**{{ secrets.AWS_REGION }} \
      **    --name ${{ secrets.AWS_CLUSTE**NAME }}

      - name: Install ku**omize
       **un**|
          curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
          sudo mv **stomize /usr/local/bin/kustomize
**     - name: Deploy frontend mani**sts
        working-directory: st**ter/frontend/k8s
        run: |
 **       kustomize edit set image f**ntend=${{ needs.build.outputs.ima** }}
          kustomize build | k**ectl apply -f -

      - name: Ve**fy frontend rollout
        run: **bectl rollout status deployment/f**ntend
